### ISSUE TITLE
Speech marks support

### ISSUE THREAD

**Issue by seblavoie** [meemalabs/laravel-text-to-speech#23]
First off, thanks for creating this package! It works great to convert text to speech. 

I am wondering if it's possible to use the [speech marks](https://docs.aws.amazon.com/polly/latest/dg/using-speechmarks.html) output option? 

I see in the code that I can pass options, but I am not sure how to format things. I've tried something like: 

```
$path = TextToSpeech::saveTo('output.txt')
        ->convert('Input text', [
            'output-format' => 'json',
            'voice-id' => 'Mathieu',
            'speech-mark-types' => 'sentence',
        ]);
```

It doesn't work. I feel like this is just not supported yet, as the config document says “Currently, mp3 is the only supported format.” 

So my question is, is there a way to do this already? And if not, I'm open to contributing with a pull request if you can just point me in the general direction as to how you'd implement this.

Thanks! :)

**Comment by luigel** [comment]
Hi @seblavoie I'll look into it.

**Comment by luigel** [comment]
Hi @seblavoie I tagged v1.4.0 adding the support for speech marks. If you can check the readme again and try it yourself and open a new issue if you encounter some 😀 thanks

**Comment by seblavoie** [comment]
Hi @luigel thanks a lot, this is perfect! And that was very fast 😄 Kudos and have a great day!
