### ISSUE TITLE
laravel 9

### ISSUE THREAD

**Issue by IvanSerevko** [meemalabs/laravel-text-to-speech#30]
### Please describe the feature

Hi, when will be able to use this plugin in Laravel 9? Thanks.

**Comment by luigel** [comment]
@IvanSerevko I created PR for laravel 9 support. #32

**Comment by IvanSerevko** [comment]
> @IvanSerevko I created PR for laravel 9 support. #32

thanks a lot

**Comment by luigel** [comment]
Released v1.5.0 https://github.com/meemalabs/laravel-text-to-speech/releases/tag/v1.5.0

**Comment by Sergiobop** [comment]
Hi @luigel, is Laravel 10 planned?
